# Generated by Django 5.2 on 2025-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField()),
                ('demo_link', models.URLField()),
                ('github_link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='instance.__class__.__name__/file_name.lower()')),
                ('status', models.CharField(choices=[('local', 'Local'), ('in_progress', 'In Progress'), ('published', 'Published')], default='in_progress', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'default_related_name': 'related_projects',
            },
        ),
    ]
